[2023-12-25T18:58:19.992+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: branch_sql_dag.create_table scheduled__2023-12-24T00:00:00+00:00 [queued]>
[2023-12-25T18:58:19.999+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: branch_sql_dag.create_table scheduled__2023-12-24T00:00:00+00:00 [queued]>
[2023-12-25T18:58:19.999+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-25T18:58:19.999+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-12-25T18:58:20.000+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-25T18:58:20.015+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-12-24 00:00:00+00:00
[2023-12-25T18:58:20.022+0000] {standard_task_runner.py:55} INFO - Started process 2153 to run task
[2023-12-25T18:58:20.026+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'branch_sql_dag', 'create_table', 'scheduled__2023-12-24T00:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/branch_sql_dag.py', '--cfg-path', '/tmp/tmp8ur3m9nl']
[2023-12-25T18:58:20.026+0000] {standard_task_runner.py:83} INFO - Job 97: Subtask create_table
[2023-12-25T18:58:20.043+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:549: DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
  option = self._get_option_from_config_file(deprecated_key, deprecated_section, key, kwargs, section)

[2023-12-25T18:58:20.084+0000] {task_command.py:376} INFO - Running <TaskInstance: branch_sql_dag.create_table scheduled__2023-12-24T00:00:00+00:00 [running]> on host 4d1993f85b22
[2023-12-25T18:58:20.111+0000] {abstractoperator.py:421} ERROR - Exception rendering Jinja template for task 'create_table', field 'sql'. Template: 'sq/CREATE_TABLE_PARTNERS.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 414, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 468, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sq/CREATE_TABLE_PARTNERS.sql
[2023-12-25T18:58:20.124+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1457, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1576, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2199, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1193, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 414, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 468, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sq/CREATE_TABLE_PARTNERS.sql
[2023-12-25T18:58:20.131+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=branch_sql_dag, task_id=create_table, execution_date=20231224T000000, start_date=20231225T185819, end_date=20231225T185820
[2023-12-25T18:58:20.144+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 97 for task create_table (sq/CREATE_TABLE_PARTNERS.sql; 2153)
[2023-12-25T18:58:20.156+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-12-25T18:58:20.186+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
